theme = "dracula_at_night"

[editor]
true-color = true
line-number = "relative"
# mouse = false
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-left = ":buffer-previous"
C-k = ":buffer-previous"
C-right = ":buffer-next"
C-l = ":buffer-next"
C-w = ":buffer-close"

"ret" = ["open_below", "normal_mode"]

[keys.select]
"ret" = ["open_below", "normal_mode"]

[keys.insert]
up = "no_op"
down = "no_op"
