theme = "catpuccin"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-left = ":buffer-previous"
C-j = ":buffer-previous"
C-right = ":buffer-next"
C-l = ":buffer-next"
C-w = ":buffer-close"

j = "move_char_left"
k = "move_visual_line_down"
i = "move_visual_line_up"
l = "move_char_right"
h = "insert_mode"

up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

# C-s = ["normal_mode", ":w"]
A-e = "save_selection"
f = ["find_next_char", "collapse_selection"]
"ret" = ["open_below", "normal_mode"]

[keys.insert]
# C-s = ["normal_mode", ":w"]

up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"


# [keys.normal.g]
# f = ["find_next_char", "collapse_selection"]
