theme = "catpuccin"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-left = ":buffer-previous"
C-h = ":buffer-previous"
C-right = ":buffer-next"
C-l = ":buffer-next"
C-w = ":buffer-close"
